### ISSUE TITLE
parses durations as ints

### ISSUE THREAD

**Issue by mattharrigan** [gosidekick/goconfig#49]
goconfig appears to parse durations as ints. Below is a minimal example that fails with `error parsing config: strconv.ParseInt: parsing "5m": invalid syntax`. If I remove the default value the help prints `int` for the type of duration. I expected this module to support all the types that go flag supports.

```
package main

import (
	"log"
	"time"

	"github.com/crgimenes/goconfig"
)

type config struct {
	Dur time.Duration `cfg:"duration" cfgDefault:"5m"`
}

func main() {
	cfg := config{}
	err := goconfig.Parse(&cfg)
	if err != nil {
		log.Fatalf("error parsing config: %v\n", err)
	}
	log.Printf("config: %v\n", cfg)
}
```

**Comment by crgimenes** [comment]
Internally the *time.Duration* type is just an int64 and I still haven't figured out a way to tell the difference via reflection. 

For now, more complex types like time.* are not supported.

**Comment by mattharrigan** [comment]
I was curious how it was done in the standard library. I don't think it uses reflection. Instead it uses the Value interface and a type alias. Very cool.
https://golang.org/pkg/flag/#Value
https://golang.org/src/flag/flag.go

Supporting the Value interface would be a great addition to this module.

**Comment by crgimenes** [comment]
I will use *field.Type.String()* in the *structtag* package and create a second set of conversion functions for modules, this should help with other types of the standard library as well.

**Comment by crgimenes** [comment]
I started an implementation that can detect more complex types In the branch *pakage_types*  but is not ready yet. I'm really not happy with the way the code is taking. I believe it is possible to achieve the same goal with much less code and less complexity.

https://github.com/crgimenes/goconfig/blob/pakage_types/structtag/structtag.go#L109

Worse than that, as the parser gets more complex it also slows down. I'm wondering if it's not a good idea to use *gogenerate* to create the code instead of an on-the-fly parser. Maybe start this in version 2 of *goconfig*

**Comment by mattharrigan** [comment]
It seems really odd to me that you would want to not follow how a very similar thing is done in the standard library. Basically if a type implements the Value interface, use it. But I have very little experience with reflection so maybe that's not possible.

**Comment by crgimenes** [comment]
How goconfig is implemented is not possible. In addition, I am not happy with the way the code ended up going, it is too big and heavy. I'm thinking of rewriting using other ideas or going to “go generate”.
